# Generated by Django 6.0.7 on 2026-07-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cvs/', verbose_name='ملف السيرة الذاتية')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_primary', models.BooleanField(default=True, verbose_name='النسخة الافتراضية')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='تحليل الذكاء الاصطناعي')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='درجة التحليل')),
            ],
            options={
                'verbose_name': 'سيرة ذاتية',
                'verbose_name_plural': 'السيرة الذاتية',
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='الجامعة')),
                ('major', models.CharField(blank=True, max_length=200, verbose_name='التخصص')),
                ('gpa', models.FloatField(default=0.0, verbose_name='المعدل التراكمي')),
                ('year_of_study', models.IntegerField(default=1, verbose_name='السنة الدراسية')),
                ('is_graduate', models.BooleanField(default=False, verbose_name='خريج')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='الجنسية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
            ],
            options={
                'verbose_name': 'متدرب',
                'verbose_name_plural': 'المتدربون',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='المعرف الفريد')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('person_type', models.CharField(choices=[('trainee', 'متدرب'), ('company', 'شركة'), ('supervisor', 'مشرف'), ('admin', 'أدمن')], max_length=20, verbose_name='نوع المستخدم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('groups', models.ManyToManyField(blank=True, related_name='trainlink_person_groups', to='auth.group', verbose_name='المجموعات')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='trainlink_person_permissions', to='auth.permission', verbose_name='صلاحيات المستخدم')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('superadmin', 'スーパーアドミン'), ('support', 'دعم')], default='support', max_length=20, verbose_name='الدور')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'أدمن',
                'verbose_name_plural': 'الأدمن',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20, verbose_name='الإجراء')),
                ('table_name', models.CharField(max_length=100, verbose_name='الجدول')),
                ('record_id', models.IntegerField(verbose_name='معرف السجل')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل المراقبة',
                'verbose_name_plural': 'سجلات المراقبة',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('commercial_id', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('industry', models.CharField(blank=True, max_length=200, verbose_name='مجال العمل')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('about', models.TextField(blank=True, verbose_name='نبذة عن الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثقة')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('purpose', models.CharField(default='registration', max_length=50, verbose_name='الغرض')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز التحقق',
                'verbose_name_plural': 'رموز التحقق',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='القسم')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='المسمى الوظيفي')),
                ('professional_experience', models.TextField(blank=True, verbose_name='الخبرة العملية')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'المشرفون',
            },
        ),
    ]
