# Generated by Django 6.0.7 on 2026-07-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainees', to='performance.supervisionassignment', verbose_name='سجل الإشراف'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='cv',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.trainee', verbose_name='المتدرب'),
        ),
    ]
