# Generated by Django 6.0.7 on 2026-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'مدير عام'), ('support', 'دعم')], default='support', max_length=20, verbose_name='الدور'),
        ),
    ]
