# Generated by Django 6.0.7 on 2026-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='حجم الشركة'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='الجامعة'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/', verbose_name='وثيقة الهوية'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='skills',
            field=models.TextField(blank=True, verbose_name='المهارات'),
        ),
    ]
