# Generated by Django 6.0.7 on 2026-07-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التخصص')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('resume_version', models.CharField(blank=True, max_length=500, verbose_name='السيرة الذاتية المستخدمة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'طلب تقديم',
                'verbose_name_plural': 'طلبات التقديم',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AcceptedTrainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200, verbose_name='القسم')),
                ('joining_date', models.DateField(verbose_name='تاريخ الالتحاق')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trainees', to='accounts.supervisorprofile', verbose_name='المشرف')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='internships.application', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'متدرب مقبول',
                'verbose_name_plural': 'المتدربون المقبولون',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('requirements', models.TextField(blank=True, verbose_name='المتطلبات')),
                ('deadline', models.DateField(verbose_name='آخر موعد للتقديم')),
                ('available_positions', models.IntegerField(default=1, verbose_name='عدد المقاعد')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('internship_type', models.CharField(choices=[('onsite', 'حضوري'), ('remote', 'عن بعد'), ('hybrid', 'مختلط')], default='onsite', max_length=20, verbose_name='النوع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('full', 'مكتمل')], default='open', max_length=20, verbose_name='الحالة')),
                ('acceptance_rate', models.FloatField(default=0.0, verbose_name='نسبة القبول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='internships.category', verbose_name='التصنيف')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.companyprofile', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فرصة تدريب',
                'verbose_name_plural': 'فرص التدريب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='الفرصة'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('internship', 'trainee')},
        ),
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='internships.internship', verbose_name='الفرصة')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_internships', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'فرصة محفوظة',
                'verbose_name_plural': 'الفرص المحفوظة',
                'unique_together': {('trainee', 'internship')},
            },
        ),
    ]
