# Generated by Django 6.0.7 on 2026-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'مسحوب')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
