# Generated by Django 6.0.7 on 2026-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مدفوع'),
        ),
    ]
