# Generated by Django 6.0.7 on 2026-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internship_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='additional_skills',
            field=models.TextField(blank=True, verbose_name='المهارات الإضافية'),
        ),
        migrations.AddField(
            model_name='internship',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='شهادة إتمام'),
        ),
        migrations.AddField(
            model_name='internship',
            name='learning_outcomes',
            field=models.TextField(blank=True, verbose_name='ما سيتعلمه المتدرب'),
        ),
        migrations.AddField(
            model_name='internship',
            name='work_days',
            field=models.CharField(blank=True, max_length=50, verbose_name='أيام العمل'),
        ),
    ]
