# Generated by Django 6.0.7 on 2026-07-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('role', models.CharField(choices=[('academic', 'أكاديمي'), ('field', 'ميداني')], default='academic', max_length=20, verbose_name='نوع الإشراف')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.supervisorprofile', verbose_name='المشرف')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_assignments', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'إشراف',
                'verbose_name_plural': 'عمليات الإشراف',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('grade', models.FloatField(default=0.0, verbose_name='التقييم')),
                ('feedback', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='ملف التقرير')),
                ('week_number', models.IntegerField(default=1, verbose_name='رقم الأسبوع')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='performance.supervisionassignment', verbose_name='الإشراف')),
            ],
            options={
                'verbose_name': 'تقرير إشرافي',
                'verbose_name_plural': 'التقارير الإشرافية',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=300, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='work_reports/', verbose_name='المرفق')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('company_feedback', models.TextField(blank=True, verbose_name='ملاحظات الشركة')),
                ('performance_rating', models.IntegerField(default=0, verbose_name='تقييم الأداء')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'تقرير يومي',
                'verbose_name_plural': 'التقارير اليومية',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر')], default='present', max_length=20, verbose_name='الحالة')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'unique_together': {('trainee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(verbose_name='رقم الأسبوع')),
                ('attendance_confirmed', models.BooleanField(default=False, verbose_name='تم تأكيد الحضور')),
                ('performance_score', models.FloatField(default=0.0, verbose_name='درجة الأداء')),
                ('comments', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('ai_summary', models.TextField(blank=True, verbose_name='ملخص الذكاء الاصطناعي')),
                ('ai_rating', models.CharField(blank=True, max_length=20, verbose_name='تقييم الذكاء الاصطناعي')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='accounts.companyprofile', verbose_name='الشركة')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'تقرير أداء أسبوعي',
                'verbose_name_plural': 'تقارير الأداء الأسبوعية',
                'ordering': ['-week_number'],
                'unique_together': {('trainee', 'company', 'week_number')},
            },
        ),
    ]
