# Generated by Django 6.0.7 on 2026-07-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatchingResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_score', models.FloatField(verbose_name='نسبة المطابقة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التوصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='internships.internship', verbose_name='الفرصة')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='accounts.trainee', verbose_name='المتدرب')),
            ],
            options={
                'verbose_name': 'نتيجة مطابقة',
                'verbose_name_plural': 'نتائج المطابقة',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=0.0, verbose_name='التقييم العام')),
                ('sections_score', models.JSONField(blank=True, null=True, verbose_name='تقييم الأقسام')),
                ('suggestions', models.JSONField(blank=True, null=True, verbose_name='الاقتراحات')),
                ('strengths', models.JSONField(blank=True, null=True, verbose_name='نقاط القوة')),
                ('weaknesses', models.JSONField(blank=True, null=True, verbose_name='نقاط الضعف')),
                ('raw_analysis', models.TextField(blank=True, verbose_name='التحليل الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.cv', verbose_name='السيرة الذاتية')),
            ],
            options={
                'verbose_name': 'تحليل سيرة ذاتية',
                'verbose_name_plural': 'تحليلات السيرة الذاتية',
            },
        ),
    ]
